import { PrismaClient } from '@prisma/client';
import { request } from 'undici';
import { AppError } from '../../utils/errors';
import { PortfolioService } from '../portfolio/portfolio.service';

export class DeployService {
  constructor(
    private prisma: PrismaClient,
    private githubToken: string,
    private portfolioService: PortfolioService
  ) {}

  async deployToGithubPages(userId: string, repoName: string, customDomain?: string) {
    const exportData = await this.portfolioService.getExportData(userId);
    const htmlContent = this.generateHtml(exportData);

    const headers = {
      'User-Agent': 'FLO-Backend',
      'Authorization': `token ${this.githubToken}`,
      'Accept': 'application/vnd.github.v3+json',
    };

    const username = exportData.github.user.login;

    // 1. Create Repository (ignore if exists, but GitHub API will error if exists)
    const { statusCode: createStatus, body: createBody } = await request(
      'https://api.github.com/user/repos',
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          name: repoName,
          description: `Portfolio generated by F.L.O for ${exportData.customData.name}`,
          auto_init: true,
        }),
      }
    );

    if (createStatus !== 201 && createStatus !== 422) {
      const error: any = await createBody.json();
      throw new AppError(`Failed to create repository: ${error.message}`, createStatus);
    }

    // 2. Push index.html
    const filePath = 'index.html';
    const { statusCode: pushStatus, body: pushBody } = await request(
      `https://api.github.com/repos/${username}/${repoName}/contents/${filePath}`,
      {
        method: 'PUT',
        headers,
        body: JSON.stringify({
          message: 'Update portfolio content',
          content: Buffer.from(htmlContent).toString('base64'),
          // branch: 'main' // default is main if auto_init: true
        }),
      }
    );

    if (pushStatus !== 200 && pushStatus !== 201) {
      const error: any = await pushBody.json();
      throw new AppError(`Failed to push content: ${error.message}`, pushStatus);
    }

    // 3. Enable GitHub Pages
    const { statusCode: pagesStatus, body: pagesBody } = await request(
      `https://api.github.com/repos/${username}/${repoName}/pages`,
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          source: {
            branch: 'main',
            path: '/',
          },
        }),
      }
    );

    // 409 means already enabled, which is fine
    if (pagesStatus !== 201 && pagesStatus !== 409) {
      const error: any = await pagesBody.json();
      // throw new AppError(`Failed to enable GitHub Pages: ${error.message}`, pagesStatus);
      // Log error but continue
      console.error('GitHub Pages enablement error:', error);
    }

    const deployedUrl = `https://${username}.github.io/${repoName}`;

    // Update Portfolio in DB
    await this.prisma.portfolio.update({
      where: { userId },
      data: {
        deployedUrl,
        repoName,
        customDomain,
      },
    });

    return {
      message: 'Deployment started',
      deployedUrl,
      repoUrl: `https://github.com/v1/${username}/${repoName}`,
    };
  }

  private generateHtml(data: any) {
    // Simple template generation logic
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${data.customData.name} | Portfolio</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900 text-white font-sans">
    <div class="max-w-4xl mx-auto py-20 px-6">
        <header class="mb-20">
            <h1 class="text-6xl font-black mb-4 bg-gradient-to-r from-blue-400 to-emerald-400 bg-clip-text text-transparent">${data.customData.name}</h1>
            <p class="text-xl text-gray-400 mb-8 max-w-2xl">${data.customData.bio}</p>
            <div class="flex gap-4">
                ${data.customData.github ? `<a href="${data.customData.github}" class="text-blue-400 hover:text-blue-300 font-bold">GitHub</a>` : ''}
                ${data.customData.linkedin ? `<a href="${data.customData.linkedin}" class="text-blue-400 hover:text-blue-300 font-bold">LinkedIn</a>` : ''}
                ${data.customData.twitter ? `<a href="${data.customData.twitter}" class="text-blue-400 hover:text-blue-300 font-bold">Twitter</a>` : ''}
            </div>
        </header>

        <section class="mb-20">
            <h2 class="text-3xl font-bold mb-10 decoration-blue-500 decoration-4 underline-offset-8 underline">Skills</h2>
            <div class="flex flex-wrap gap-3">
                ${data.skills.map((skill: string) => `<span class="px-4 py-2 bg-gray-800 rounded-full border border-gray-700 font-medium">${skill}</span>`).join('')}
            </div>
        </section>

        <section>
            <h2 class="text-3xl font-bold mb-10 decoration-emerald-500 decoration-4 underline-offset-8 underline">Projects</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                ${data.github.repos.map((repo: any) => `
                    <div class="p-8 bg-gray-800 rounded-2xl border border-gray-700 hover:border-blue-500 transition-all group">
                        <h3 class="text-2xl font-bold mb-4 group-hover:text-blue-400">${repo.name}</h3>
                        <p class="text-gray-400 mb-6 line-clamp-2">${repo.description || 'No description available.'}</p>
                        <div class="flex justify-between items-center text-sm font-bold">
                            <span class="text-emerald-400">${repo.language || 'Code'}</span>
                            <a href="${repo.html_url}" class="px-4 py-2 bg-blue-600 rounded-lg hover:bg-blue-500 transition-colors">View Project</a>
                        </div>
                    </div>
                `).join('')}
            </div>
        </section>

        <footer class="mt-40 pt-10 border-t border-gray-800 text-center text-gray-500 text-sm">
            Powered by <a href="#" class="text-blue-400 hover:underline">F.L.O Portfolio Generator</a>
        </footer>
    </div>
</body>
</html>
    `;
  }
}
